# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [9]:
# Read `tic-tac-toe.csv` into a dataframe.
import pandas as pd
df = pd.read_csv("tic-tac-toe.csv")
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [10]:
# Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
df.info()
df.describe(include='all')
df.nunique()
df.sample(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

    TL TM TR ML MM MR BL BM BR  class
698  x  o  b  x  o  x  o  o  x  False
935  b  b  o  x  x  o  b  x  o  False
189  x  o  b  x  x  x  b  o  o   True
943  x  x  o  o  o  x  x  x  o  False
458  o  b  o  x  x  x  x  o  b   True
696  x  o  o  b  o  x  x  o  x  False
384  o  o  x  o  x  x  b  b  x   True
804  o  o  x  x  o  x  x  b  o  False
827  o  o  o  x  b  x  b  x  b  False
348  o  x  b  x  x  o  o  x  b   True

In [11]:
#Convert the categorical values to numeric in all columns.
mapping = {'x': 1, 'o': -1, 'b': 0}

for col in df.columns[:-1]:   # todas menos 'class'
    df[col] = df[col].map(mapping)

df['class'] = df['class'].map({True: 1, False: 0})

In [12]:
#Separate the inputs and output.

X = df.drop('class', axis=1).values
y = df['class'].values

In [13]:
# Normalize the input data.

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [14]:
# Split the training and test data.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [17]:
!pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.20.0-cp313-cp313-win_amd64.whl.metadata (4.6 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\con2m\anaconda3\lib\site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\con2m\anaconda3\lib\site-packages (from tensorflow) (5.29.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\con2m\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\con2m\anaconda3\lib\site-packages (from tensorflow) (72.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\con2m\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\con2m\anaconda3\lib\site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\con2m\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.78.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Collecting tensorboard~=2.20.0 (from tensorflow)
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting keras>=3.10.0 (from tensorflow)
  Downloading keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\con2m\anaconda3\lib\site-packages (from tensorflow) (2.1.3)
Requirement already satisfied: h5py>=3.11.0 in c:\users\con2m\anaconda3\lib\site-packages (from tensorflow) (3.12.1)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\con2m\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\con2m\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\con2m\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\con2m\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.4.26)
Requirement already satisfied: markdown>=2.6.8 in c:\users\con2m\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.8)
Requirement already satisfied: pillow in c:\users\con2m\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (11.1.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard~=2.20.0->tensorflow)
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\con2m\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\con2m\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\con2m\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Collecting namex (from keras>=3.10.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.10.0->tensorflow)
  Downloading optree-0.18.0-cp313-cp313-win_amd64.whl.metadata (35 kB)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\con2m\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\con2m\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\con2m\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\con2m\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.0)
Downloading tensorflow-2.20.0-cp313-cp313-win_amd64.whl (332.0 MB)
   ---------------------------------------- 0.0/332.0 MB ? eta -:--:--
   - -------------------------------------- 15.2/332.0 MB 82.0 MB/s eta 0:00:04
   --- ------------------------------------ 31.7/332.0 MB 80.1 MB/s eta 0:00:04
   ----- ---------------------------------- 48.5/332.0 MB 79.1 MB/s eta 0:00:04
   ------- -------------------------------- 65.8/332.0 MB 79.0 MB/s eta 0:00:04
   --------- ------------------------------ 81.8/332.0 MB 79.0 MB/s eta 0:00:04
   ----------- ---------------------------- 97.8/332.0 MB 78.9 MB/s eta 0:00:03
   ------------- ------------------------- 114.8/332.0 MB 79.0 MB/s eta 0:00:03
   --------------- ----------------------- 130.0/332.0 MB 78.7 MB/s eta 0:00:03
   ----------------- --------------------- 147.3/332.0 MB 78.7 MB/s eta 0:00:03
   ------------------- ------------------- 163.8/332.0 MB 79.0 MB/s eta 0:00:03
   --------------------- ----------------- 179.3/332.0 MB 78.7 MB/s eta 0:00:02
   ---------------------- ---------------- 195.0/332.0 MB 78.8 MB/s eta 0:00:02
   ------------------------ -------------- 211.3/332.0 MB 78.6 MB/s eta 0:00:02
   -------------------------- ------------ 227.0/332.0 MB 78.6 MB/s eta 0:00:02
   ---------------------------- ---------- 244.1/332.0 MB 78.6 MB/s eta 0:00:02
   ------------------------------ -------- 259.8/332.0 MB 78.7 MB/s eta 0:00:01
   -------------------------------- ------ 276.8/332.0 MB 78.4 MB/s eta 0:00:01
   ---------------------------------- ---- 291.5/332.0 MB 78.2 MB/s eta 0:00:01
   ------------------------------------ -- 308.0/332.0 MB 78.5 MB/s eta 0:00:01
   --------------------------------------  324.3/332.0 MB 78.4 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 78.2 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 78.2 MB/s eta 0:00:01
   --------------------------------------- 332.0/332.0 MB 67.9 MB/s eta 0:00:00
Downloading grpcio-1.78.0-cp313-cp313-win_amd64.whl (4.8 MB)
   ---------------------------------------- 0.0/4.8 MB ? eta -:--:--
   ---------------------------------------- 4.8/4.8 MB 73.6 MB/s eta 0:00:00
Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl (212 kB)
Downloading tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ---------------------------------------- 5.5/5.5 MB 74.5 MB/s eta 0:00:00
Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Downloading absl_py-2.4.0-py3-none-any.whl (135 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading keras-3.13.2-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 67.8 MB/s eta 0:00:00
Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
   ---------------------------------------- 0.0/26.4 MB ? eta -:--:--
   ------------------------- -------------- 17.0/26.4 MB 85.1 MB/s eta 0:00:01
   ---------------------------------------- 26.4/26.4 MB 70.6 MB/s eta 0:00:00
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.18.0-cp313-cp313-win_amd64.whl (314 kB)
Installing collected packages: namex, libclang, flatbuffers, termcolor, tensorboard-data-server, optree, opt_einsum, ml_dtypes, grpcio, google_pasta, gast, astunparse, absl-py, tensorboard, keras, tensorflow

   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   --------------- ------------------------  6/16 [opt_einsum]
   -------------------- -------------------  8/16 [grpcio]
   ---------------------- -----------------  9/16 [google_pasta]
   ------------------------------ --------- 12/16 [absl-py]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ---------------------------------------- 16/16 [tensorflow]

Successfully installed absl-py-2.4.0 astunparse-1.6.3 flatbuffers-25.12.19 gast-0.7.0 google_pasta-0.2.0 grpcio-1.78.0 keras-3.13.2 libclang-18.1.1 ml_dtypes-0.5.4 namex-0.1.0 opt_einsum-3.4.0 optree-0.18.0 tensorboard-2.20.0 tensorboard-data-server-0.7.2 tensorflow-2.20.0 termcolor-3.3.0

In [18]:
# Create a `Sequential` model.

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
#Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.

model = Sequential()

model.add(Dense(32, activation='relu', input_shape=(9,)))

model.add(Dense(16, activation='relu'))

model.add(Dense(2, activation='softmax'))

c:\Users\con2m\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
# Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [24]:
# Make predictions

predictions = model.predict(X_test)
predicted_classes = predictions.argmax(axis=1)
print(predicted_classes)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
[1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1
 1 1 0 1 1 1 1]

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [25]:
# Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.

model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(9,)))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(2, activation='softmax'))

c:\Users\con2m\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [26]:
# Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.

from tensorflow.keras.optimizers import Adam
optimizer = Adam(learning_rate=0.001)
model.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [27]:
#  Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

model.fit(X_train, y_train, epochs=100)

Epoch 1/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6645 - loss: 0.6386
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7311 - loss: 0.5688
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7820 - loss: 0.5210
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8003 - loss: 0.4724
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8211 - loss: 0.4207
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8642 - loss: 0.3663
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8969 - loss: 0.3044
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9217 - loss: 0.2448
Epoch 9/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9713 - loss: 0.1895
Epoch 10/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9856 - loss: 0.1413
Epoch 11/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9896 - loss: 0.1012
Epoch 12/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9922 - loss: 0.0758
Epoch 13/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9948 - loss: 0.0557
Epoch 14/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9948 - loss: 0.0449
Epoch 15/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9987 - loss: 0.0316
Epoch 16/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9987 - loss: 0.0252
Epoch 17/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9987 - loss: 0.0197
Epoch 18/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0158
Epoch 19/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0128
Epoch 20/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0106
Epoch 21/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0091
Epoch 22/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0076
Epoch 23/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0065
Epoch 24/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0057
Epoch 25/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0050
Epoch 26/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0044
Epoch 27/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0039
Epoch 28/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0035
Epoch 29/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0032
Epoch 30/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0029
Epoch 31/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0026
Epoch 32/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0024
Epoch 33/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0022
Epoch 34/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0020
Epoch 35/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0019
Epoch 36/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0017
Epoch 37/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0016
Epoch 38/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0015
Epoch 39/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0014
Epoch 40/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0013
Epoch 41/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0012
Epoch 42/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0011
Epoch 43/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0011
Epoch 44/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0010
Epoch 45/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 9.4884e-04
Epoch 46/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 8.8678e-04
Epoch 47/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 8.4213e-04
Epoch 48/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 7.9974e-04
Epoch 49/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 7.5749e-04
Epoch 50/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 7.1848e-04
Epoch 51/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 6.8356e-04
Epoch 52/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 6.5212e-04
Epoch 53/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 6.1892e-04
Epoch 54/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 5.9070e-04
Epoch 55/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.6444e-04
Epoch 56/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 5.4144e-04
Epoch 57/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 5.1560e-04
Epoch 58/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.9410e-04
Epoch 59/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.7481e-04
Epoch 60/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.5281e-04
Epoch 61/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.3823e-04
Epoch 62/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.1857e-04
Epoch 63/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.0255e-04
Epoch 64/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.8772e-04
Epoch 65/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.7108e-04
Epoch 66/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.5819e-04
Epoch 67/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.4530e-04
Epoch 68/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.3150e-04
Epoch 69/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.2385e-04
Epoch 70/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.0869e-04
Epoch 71/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.9749e-04
Epoch 72/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.8801e-04
Epoch 73/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.7762e-04
Epoch 74/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.7019e-04
Epoch 75/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.6133e-04
Epoch 76/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.5067e-04
Epoch 77/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.4413e-04
Epoch 78/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.3551e-04
Epoch 79/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.2823e-04
Epoch 80/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.2088e-04
Epoch 81/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.1363e-04
Epoch 82/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.0669e-04
Epoch 83/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.0046e-04
Epoch 84/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.9460e-04
Epoch 85/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.8906e-04
Epoch 86/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.8316e-04
Epoch 87/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.7839e-04
Epoch 88/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.7279e-04
Epoch 89/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.6791e-04
Epoch 90/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.6309e-04
Epoch 91/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.5917e-04
Epoch 92/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.5447e-04
Epoch 93/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.4997e-04
Epoch 94/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.4691e-04
Epoch 95/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.4187e-04
Epoch 96/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.3781e-04
Epoch 97/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.3488e-04
Epoch 98/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.3101e-04
Epoch 99/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.2772e-04
Epoch 100/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.2386e-04

In [28]:
# Evaluate the model

model.evaluate(X_test, y_test)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9844 - loss: 0.0284

[0.028369873762130737, 0.984375]

**Which approach(es) did you find helpful to improve your model performance?**

In [29]:
# The model performance is really good. We have an accuracy of 0.98 on the test set. This means that the model is able to correctly predict the outcome of a tic-tac-toe game 98% of the time. This is a very good performance for a simple neural network model.