# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [5]:
import tensorflow as tf

2025-03-23 14:01:48.936498: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [6]:
tf.__version__

'2.12.0'

In [22]:
# basic libraries
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
file_path = "tic-tac-toe.csv"
data = pd.read_csv(file_path)
df = data.copy()

In [4]:
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [8]:
df["class"] = df["class"].astype(int)
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o      1
1  x  x  x  x  o  o  o  x  o      1
2  x  x  x  x  o  o  o  o  x      1
3  x  x  x  x  o  o  o  b  b      1
4  x  x  x  x  o  o  b  o  b      1

In [ ]:
y = df["class"] #separate output

In [ ]:
prep_X = df.drop("class", axis=1)
# Map categorical values to numbers
mapping = {'x': 1, 'o': -1, 'b': 0}
X = prep_X.applymap(lambda mark: mapping[mark]) #separate input

In [15]:
df = pd.concat([X,y], axis=1)
df.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1  -1  -1   1  -1  -1      1
1   1   1   1   1  -1  -1  -1   1  -1      1
2   1   1   1   1  -1  -1  -1  -1   1      1
3   1   1   1   1  -1  -1  -1   0   0      1
4   1   1   1   1  -1  -1   0  -1   0      1

In [20]:
#normalise the input data
scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [ ]:
# split the training and test data
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.3, random_state=42 )

In [23]:
# create a sequential model
model = Sequential()

In [26]:
# adding several layers
# Add layers one by one
model.add(Dense(9, activation='relu', input_shape = (9,)))  # Input layer
model.add(Dense(16, activation='relu'))   # Hidden layer
model.add(Dense(32, activation='relu'))   # Hidden layer
model.add(Dense(2, activation='softmax'))  # Output layer for classification

In [29]:
# compiling the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [30]:
model.fit(X_train, y_train)

21/21 [==============================] - 1s 1ms/step - loss: 0.6592 - accuracy: 0.5463

In [34]:
# evaluating the neural network model with test data
val_loss, val_acc = model.evaluate(X_test, y_test)

9/9 [==============================] - 0s 1ms/step - loss: 0.6447 - accuracy: 0.5903

In [32]:
print(val_loss, val_acc)

0.64469313621521 0.5902777910232544

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [49]:
model.save('tic_tac_toe')
new_model = tf.keras.models.load_model('tic_tac_toe')

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: tic_tac_toe/assets

INFO:tensorflow:Assets written to: tic_tac_toe/assets

In [57]:
predictions = new_model.predict([X_test])

9/9 [==============================] - 0s 1ms/step

In [60]:
print(np.argmax(predictions[60]))

1

In [61]:
len(predictions)

288

In [62]:
n = 0
predictions_list = []
while n < len(predictions):
    predictions_list.append(np.argmax(predictions[n]))
    n += 1

predictions_series = pd.Series(predictions_list)

In [66]:
eval_df = pd.DataFrame({"actual":y_test,"pred":predictions_series})
eval_df.head()

   actual  pred
0     NaN   1.0
1     NaN   1.0
2     1.0   1.0
3     NaN   1.0
4     NaN   1.0

In [70]:
eval_df['match'] = eval_df['actual'].fillna(-1) == eval_df['pred']

In [71]:
eval_df.head()

   actual  pred  match
0     NaN   1.0  False
1     NaN   1.0  False
2     1.0   1.0   True
3     NaN   1.0  False
4     NaN   1.0  False

In [72]:
eval_df.match.value_counts()

match
False    425
True      73
Name: count, dtype: int64

Predictions are very bad.

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [ ]:
# more layers

In [ ]:
# adjust learning rate

In [ ]:
# adust the number of epoch when you fit the training data to the model

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here