# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

### Read tic-tac-toe.csv into a dataframe.

In [28]:
import pandas as pd
df = pd.read_csv('tic-tac-toe.csv')

### Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.

In [24]:
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [3]:
df.tail()

    TL TM TR ML MM MR BL BM BR  class
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

In [5]:
df.columns

Index(['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR', 'class'], dtype='object')

In [18]:
for element in df.columns:
    # print(f'For the column {element} its unique values are {df[element].unique()}')
    print(f"{element} value counts are {df[element].value_counts()}")

TL value counts are TL
x    418
o    335
b    205
Name: count, dtype: int64
TM value counts are TM
x    378
o    330
b    250
Name: count, dtype: int64
TR value counts are TR
x    418
o    335
b    205
Name: count, dtype: int64
ML value counts are ML
x    378
o    330
b    250
Name: count, dtype: int64
MM value counts are MM
x    458
o    340
b    160
Name: count, dtype: int64
MR value counts are MR
x    378
o    330
b    250
Name: count, dtype: int64
BL value counts are BL
x    418
o    335
b    205
Name: count, dtype: int64
BM value counts are BM
x    378
o    330
b    250
Name: count, dtype: int64
BR value counts are BR
x    418
o    335
b    205
Name: count, dtype: int64
class value counts are class
True     626
False    332
Name: count, dtype: int64

### Convert the categorical values to numeric in all columns.

In [29]:
numeric_circles_blanks_and_xs = {'x':-1,'o':1,'b':0}
for element in df.iloc[:,:-1].columns:
    df[element] = df[element].map(numeric_circles_blanks_and_xs)
df['class'] = [1 if x==True else 0 for x in df['class']]
df

     TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0    -1  -1  -1  -1   1   1  -1   1   1      1
1    -1  -1  -1  -1   1   1   1  -1   1      1
2    -1  -1  -1  -1   1   1   1   1  -1      1
3    -1  -1  -1  -1   1   1   1   0   0      1
4    -1  -1  -1  -1   1   1   0   1   0      1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
953   1  -1  -1  -1   1   1   1  -1  -1      0
954   1  -1   1  -1  -1   1  -1   1  -1      0
955   1  -1   1  -1   1  -1  -1   1  -1      0
956   1  -1   1   1  -1  -1  -1   1  -1      0
957   1   1  -1  -1  -1   1   1  -1  -1      0

[958 rows x 10 columns]

### Separate the inputs and output.

In [31]:
X = df.iloc[:,:-1]
y = df['class']

### Normalize the input data.

##### It is already normalized with our previous steps

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

### Split the training and test data.

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

### Create a `Sequential` model (Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer)

In [48]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

smodel = Sequential([Dense(64, activation='tanh', input_shape=(X_train.shape[1],))
                    ,Dense(32, activation='relu')
                    ,Dense(2, activation='softmax')])

### Compile the model using adam as the optimizer and sparse_categorical_crossentropy as the loss function. For metrics, use accuracy for now.

In [49]:
from tensorflow.keras.optimizers import Adam

smodel.compile(optimizer=Adam()
               ,loss='sparse_categorical_crossentropy' #
               # ,loss='binary_crossentropy'
               ,metrics=['accuracy']
              )

### Fit the training data.

In [50]:
fittef_smodel = smodel.fit(X_train, y_train, validation_split=0.2, epochs= 20, batch_size=32, verbose=1)

Epoch 1/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.6432 - loss: 0.6539 - val_accuracy: 0.7153 - val_loss: 0.5752
Epoch 2/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7309 - loss: 0.5584 - val_accuracy: 0.7569 - val_loss: 0.5410
Epoch 3/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7678 - loss: 0.5101 - val_accuracy: 0.7569 - val_loss: 0.5305
Epoch 4/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7631 - loss: 0.4891 - val_accuracy: 0.7708 - val_loss: 0.5199
Epoch 5/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7783 - loss: 0.4710 - val_accuracy: 0.7847 - val_loss: 0.4916
Epoch 6/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7979 - loss: 0.4359 - val_accuracy: 0.7986 - val_loss: 0.4693
Epoch 7/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8346 - loss: 0.3897 - val_accuracy: 0.8125 - val_loss: 0.4352
Epoch 8/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8703 - loss: 0.3536 - val_accuracy: 0.8333 - val_loss: 0.3995
Epoch 9/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8819 - loss: 0.3340 - val_accuracy: 0.8611 - val_loss: 0.3441
Epoch 10/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9111 - loss: 0.3181 - val_accuracy: 0.8958 - val_loss: 0.2939
Epoch 11/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9501 - loss: 0.2442 - val_accuracy: 0.9444 - val_loss: 0.2411
Epoch 12/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9648 - loss: 0.2168 - val_accuracy: 0.9583 - val_loss: 0.2092
Epoch 13/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9800 - loss: 0.1681 - val_accuracy: 0.9792 - val_loss: 0.1683
Epoch 14/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9880 - loss: 0.1301 - val_accuracy: 0.9861 - val_loss: 0.1459
Epoch 15/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9823 - loss: 0.1233 - val_accuracy: 0.9861 - val_loss: 0.1255
Epoch 16/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9885 - loss: 0.0840 - val_accuracy: 0.9861 - val_loss: 0.1151
Epoch 17/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9910 - loss: 0.0747 - val_accuracy: 0.9861 - val_loss: 0.1032
Epoch 18/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9864 - loss: 0.0729 - val_accuracy: 0.9861 - val_loss: 0.0946
Epoch 19/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9841 - loss: 0.0730 - val_accuracy: 0.9861 - val_loss: 0.0924
Epoch 20/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9913 - loss: 0.0519 - val_accuracy: 0.9861 - val_loss: 0.0889

### Evaluate your neural network model with the test data.

In [52]:
test_loss, test_acc = smodel.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", test_acc)
print("Test loss:", test_loss)

Test accuracy: 0.9750000238418579
Test loss: 0.09161963313817978

### Save your model as tic-tac-toe.model.keras

In [54]:
smodel.save("tic-tac-toe.model.keras")

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [55]:
from tensorflow.keras.models import load_model

model = load_model("tic-tac-toe.model.keras")

In [67]:
X_rand = X_test.sample(n=5, random_state=None)
y_true = y_test.loc[X_rand.index]

In [71]:
X_rand

     TL  TM  TR  ML  MM  MR  BL  BM  BR
2    -1  -1  -1  -1   1   1   1   1  -1
328   1  -1   1  -1   1   1  -1  -1  -1
136  -1   1  -1   0  -1   1  -1   1   0
507   0  -1   1   1  -1   0   0  -1   0
298   1  -1  -1   1  -1  -1  -1   1   1

In [72]:
y_true

2      1
328    1
136    1
507    1
298    1
Name: class, dtype: int64

In [73]:
y_prob = model.predict(X_rand).ravel()
y_pred = (y_prob >= 0.5).astype(int)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

In [74]:
y_pred

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

My model obtained high accuracy acc>0.95 and low loss loss <0.1
My results are:

Test accuracy: 0.9750000238418579
Test loss: 0.09161963313817978

**Which approach(es) did you find helpful to improve your model performance?**

In [76]:
# Add more layers and more epochs