# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [2]:
# your code here
import pandas as pd
df = pd.read_csv("tic-tac-toe.csv")
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [3]:
df.describe()

         TL   TM   TR   ML   MM   MR   BL   BM   BR class
count   958  958  958  958  958  958  958  958  958   958
unique    3    3    3    3    3    3    3    3    3     2
top       x    x    x    x    x    x    x    x    x  True
freq    418  378  418  378  458  378  418  378  418   626

In [8]:
df.isna().sum()

TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

In [16]:
df = pd.get_dummies(df, drop_first=True)
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   class   958 non-null    bool
 1   TL_o    958 non-null    bool
 2   TL_x    958 non-null    bool
 3   TM_o    958 non-null    bool
 4   TM_x    958 non-null    bool
 5   TR_o    958 non-null    bool
 6   TR_x    958 non-null    bool
 7   ML_o    958 non-null    bool
 8   ML_x    958 non-null    bool
 9   MM_o    958 non-null    bool
 10  MM_x    958 non-null    bool
 11  MR_o    958 non-null    bool
 12  MR_x    958 non-null    bool
 13  BL_o    958 non-null    bool
 14  BL_x    958 non-null    bool
 15  BM_o    958 non-null    bool
 16  BM_x    958 non-null    bool
 17  BR_o    958 non-null    bool
 18  BR_x    958 non-null    bool
dtypes: bool(19)
memory usage: 17.9 KB

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [51]:
# your code here
predictors = df.drop("class", axis=1)
target = df["class"].astype(int)

In [52]:
target.value_counts()

class
1    626
0    332
Name: count, dtype: int64

In [53]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,TL_o,TL_x,TM_o,TM_x,TR_o,TR_x,ML_o,ML_x,MM_o,MM_x,MR_o,MR_x,BL_o,BL_x,BM_o,BM_x,BR_o,BR_x
0,-0.732912,1.136009,-0.72452,1.238059,-0.732912,1.136009,-0.72452,1.238059,1.347498,-0.956579,1.378783,-0.806873,-0.732912,1.136009,1.378783,-0.806873,1.362997,-0.879355
1,-0.732912,1.136009,-0.72452,1.238059,-0.732912,1.136009,-0.72452,1.238059,1.347498,-0.956579,1.378783,-0.806873,1.362997,-0.879355,-0.724520,1.238059,1.362997,-0.879355
2,-0.732912,1.136009,-0.72452,1.238059,-0.732912,1.136009,-0.72452,1.238059,1.347498,-0.956579,1.378783,-0.806873,1.362997,-0.879355,1.378783,-0.806873,-0.732912,1.136009
3,-0.732912,1.136009,-0.72452,1.238059,-0.732912,1.136009,-0.72452,1.238059,1.347498,-0.956579,1.378783,-0.806873,1.362997,-0.879355,-0.724520,-0.806873,-0.732912,-0.879355
4,-0.732912,1.136009,-0.72452,1.238059,-0.732912,1.136009,-0.72452,1.238059,1.347498,-0.956579,1.378783,-0.806873,-0.732912,-0.879355,1.378783,-0.806873,-0.732912,-0.879355

In [54]:
n_cols = predictors_norm.shape[1]

In [31]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [59]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(50, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(2, activation = 'softmax'))
    
    # compile model
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
    return model

In [60]:
model = regression_model()

/Users/yasaman.nj/Library/Python/3.9/lib/python/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size= 0.3, random_state=42)

In [62]:
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100

21/21 - 0s - 15ms/step - loss: 0.6617
Epoch 2/100
21/21 - 0s - 822us/step - loss: 0.5638
Epoch 3/100
21/21 - 0s - 800us/step - loss: 0.5082
Epoch 4/100
21/21 - 0s - 739us/step - loss: 0.4608
Epoch 5/100
21/21 - 0s - 676us/step - loss: 0.4143
Epoch 6/100
21/21 - 0s - 686us/step - loss: 0.3662
Epoch 7/100
21/21 - 0s - 747us/step - loss: 0.3208
Epoch 8/100
21/21 - 0s - 1ms/step - loss: 0.2737
Epoch 9/100
21/21 - 0s - 1ms/step - loss: 0.2266
Epoch 10/100
21/21 - 0s - 888us/step - loss: 0.1851
Epoch 11/100
21/21 - 0s - 699us/step - loss: 0.1497
Epoch 12/100
21/21 - 0s - 671us/step - loss: 0.1198
Epoch 13/100
21/21 - 0s - 674us/step - loss: 0.0969
Epoch 14/100
21/21 - 0s - 729us/step - loss: 0.0792
Epoch 15/100
21/21 - 0s - 701us/step - loss: 0.0646
Epoch 16/100
21/21 - 0s - 716us/step - loss: 0.0533
Epoch 17/100
21/21 - 0s - 701us/step - loss: 0.0448
Epoch 18/100
21/21 - 0s - 721us/step - loss: 0.0373
Epoch 19/100
21/21 - 0s - 728us/step - loss: 0.0320
Epoch 20/100
21/21 - 0s - 758us/step - loss: 0.0272
Epoch 21/100
21/21 - 0s - 733us/step - loss: 0.0232
Epoch 22/100
21/21 - 0s - 749us/step - loss: 0.0203
Epoch 23/100
21/21 - 0s - 765us/step - loss: 0.0177
Epoch 24/100
21/21 - 0s - 781us/step - loss: 0.0155
Epoch 25/100
21/21 - 0s - 804us/step - loss: 0.0138
Epoch 26/100
21/21 - 0s - 769us/step - loss: 0.0121
Epoch 27/100
21/21 - 0s - 761us/step - loss: 0.0110
Epoch 28/100
21/21 - 0s - 740us/step - loss: 0.0099
Epoch 29/100
21/21 - 0s - 767us/step - loss: 0.0090
Epoch 30/100
21/21 - 0s - 744us/step - loss: 0.0081
Epoch 31/100
21/21 - 0s - 748us/step - loss: 0.0074
Epoch 32/100
21/21 - 0s - 767us/step - loss: 0.0068
Epoch 33/100
21/21 - 0s - 756us/step - loss: 0.0062
Epoch 34/100
21/21 - 0s - 777us/step - loss: 0.0058
Epoch 35/100
21/21 - 0s - 752us/step - loss: 0.0053
Epoch 36/100
21/21 - 0s - 784us/step - loss: 0.0049
Epoch 37/100
21/21 - 0s - 755us/step - loss: 0.0045
Epoch 38/100
21/21 - 0s - 742us/step - loss: 0.0042
Epoch 39/100
21/21 - 0s - 758us/step - loss: 0.0040
Epoch 40/100
21/21 - 0s - 722us/step - loss: 0.0037
Epoch 41/100
21/21 - 0s - 713us/step - loss: 0.0035
Epoch 42/100
21/21 - 0s - 718us/step - loss: 0.0032
Epoch 43/100
21/21 - 0s - 715us/step - loss: 0.0030
Epoch 44/100
21/21 - 0s - 708us/step - loss: 0.0029
Epoch 45/100
21/21 - 0s - 690us/step - loss: 0.0027
Epoch 46/100
21/21 - 0s - 674us/step - loss: 0.0026
Epoch 47/100
21/21 - 0s - 699us/step - loss: 0.0024
Epoch 48/100
21/21 - 0s - 722us/step - loss: 0.0023
Epoch 49/100
21/21 - 0s - 699us/step - loss: 0.0022
Epoch 50/100
21/21 - 0s - 678us/step - loss: 0.0021
Epoch 51/100
21/21 - 0s - 700us/step - loss: 0.0020
Epoch 52/100
21/21 - 0s - 704us/step - loss: 0.0019
Epoch 53/100
21/21 - 0s - 692us/step - loss: 0.0018
Epoch 54/100
21/21 - 0s - 692us/step - loss: 0.0017
Epoch 55/100
21/21 - 0s - 699us/step - loss: 0.0016
Epoch 56/100
21/21 - 0s - 723us/step - loss: 0.0016
Epoch 57/100
21/21 - 0s - 704us/step - loss: 0.0015
Epoch 58/100
21/21 - 0s - 666us/step - loss: 0.0014
Epoch 59/100
21/21 - 0s - 687us/step - loss: 0.0014
Epoch 60/100
21/21 - 0s - 698us/step - loss: 0.0013
Epoch 61/100
21/21 - 0s - 706us/step - loss: 0.0013
Epoch 62/100
21/21 - 0s - 677us/step - loss: 0.0012
Epoch 63/100
21/21 - 0s - 711us/step - loss: 0.0012
Epoch 64/100
21/21 - 0s - 690us/step - loss: 0.0011
Epoch 65/100
21/21 - 0s - 710us/step - loss: 0.0011
Epoch 66/100
21/21 - 0s - 695us/step - loss: 0.0010
Epoch 67/100
21/21 - 0s - 699us/step - loss: 0.0010
Epoch 68/100
21/21 - 0s - 690us/step - loss: 9.7390e-04
Epoch 69/100
21/21 - 0s - 682us/step - loss: 9.4658e-04
Epoch 70/100
21/21 - 0s - 666us/step - loss: 9.1160e-04
Epoch 71/100
21/21 - 0s - 693us/step - loss: 8.7950e-04
Epoch 72/100
21/21 - 0s - 718us/step - loss: 8.4979e-04
Epoch 73/100
21/21 - 0s - 706us/step - loss: 8.2195e-04
Epoch 74/100
21/21 - 0s - 697us/step - loss: 7.9497e-04
Epoch 75/100
21/21 - 0s - 692us/step - loss: 7.7173e-04
Epoch 76/100
21/21 - 0s - 704us/step - loss: 7.4268e-04
Epoch 77/100
21/21 - 0s - 704us/step - loss: 7.1974e-04
Epoch 78/100
21/21 - 0s - 704us/step - loss: 6.9585e-04
Epoch 79/100
21/21 - 0s - 702us/step - loss: 6.7371e-04
Epoch 80/100
21/21 - 0s - 692us/step - loss: 6.5710e-04
Epoch 81/100
21/21 - 0s - 681us/step - loss: 6.3113e-04
Epoch 82/100
21/21 - 0s - 696us/step - loss: 6.1476e-04
Epoch 83/100
21/21 - 0s - 723us/step - loss: 6.0227e-04
Epoch 84/100
21/21 - 0s - 728us/step - loss: 5.7990e-04
Epoch 85/100
21/21 - 0s - 726us/step - loss: 5.6264e-04
Epoch 86/100
21/21 - 0s - 735us/step - loss: 5.4501e-04
Epoch 87/100
21/21 - 0s - 756us/step - loss: 5.2969e-04
Epoch 88/100
21/21 - 0s - 755us/step - loss: 5.1510e-04
Epoch 89/100
21/21 - 0s - 750us/step - loss: 4.9990e-04
Epoch 90/100
21/21 - 0s - 753us/step - loss: 4.8737e-04
Epoch 91/100
21/21 - 0s - 734us/step - loss: 4.7381e-04
Epoch 92/100
21/21 - 0s - 748us/step - loss: 4.6123e-04
Epoch 93/100
21/21 - 0s - 760us/step - loss: 4.4557e-04
Epoch 94/100
21/21 - 0s - 761us/step - loss: 4.3543e-04
Epoch 95/100
21/21 - 0s - 863us/step - loss: 4.2374e-04
Epoch 96/100
21/21 - 0s - 778us/step - loss: 4.1193e-04
Epoch 97/100
21/21 - 0s - 777us/step - loss: 4.0036e-04
Epoch 98/100
21/21 - 0s - 782us/step - loss: 3.9156e-04
Epoch 99/100
21/21 - 0s - 786us/step - loss: 3.8030e-04
Epoch 100/100
21/21 - 0s - 780us/step - loss: 3.7232e-04

In [63]:
y_pred = model.predict(X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step

In [73]:
# Calculate and print regression metrics
from sklearn.metrics import accuracy_score
import numpy as np

y_pred_classes = np.argmax(y_pred, axis=1)
accuracy = accuracy_score(y_test, y_pred_classes)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9861

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [77]:
# your code here
 #Choose a few random rows from the test set
sample_idx = np.random.choice(len(X_test), size=10, replace=False)
print(sample_idx)
X_sample = X_test.iloc[sample_idx]
y_sample = y_test.iloc[sample_idx]

predictions = model.predict(X_sample)
predicted_classes = np.argmax(predictions, axis=1)

for i, (actual, pred) in enumerate(zip(y_sample, predicted_classes)):
    print(f"Row {sample_idx[i]}: actual={actual}, predicted={pred}")
    print("Correct" if actual == pred else "Incorrect")

[107 246  87 140 150  34  13 115  29 264]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
Row 107: actual=1, predicted=1
Correct
Row 246: actual=0, predicted=0
Correct
Row 87: actual=0, predicted=0
Correct
Row 140: actual=1, predicted=1
Correct
Row 150: actual=1, predicted=1
Correct
Row 34: actual=0, predicted=0
Correct
Row 13: actual=0, predicted=1
Incorrect
Row 115: actual=1, predicted=1
Correct
Row 29: actual=1, predicted=1
Correct
Row 264: actual=0, predicted=0
Correct

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [ ]:
# your code here

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here