# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('tic-tac-toe.csv')

In [22]:
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

In [24]:
df.columns

Index(['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR', 'class'], dtype='object')

In [25]:

map = {'x': 1, 'o': -1, 'b': 0}

df_num = df.copy()

for col in df_num.columns:
    if col != 'class': 
        df_num[col] = df_num[col].map(map)

df_num['class'] = df['class'].astype(int)
df_num.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1  -1  -1   1  -1  -1      1
1   1   1   1   1  -1  -1  -1   1  -1      1
2   1   1   1   1  -1  -1  -1  -1   1      1
3   1   1   1   1  -1  -1  -1   0   0      1
4   1   1   1   1  -1  -1   0  -1   0      1

In [26]:
X = df_num.drop(columns=['class'])
y = df_num['class']

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout


model = Sequential([
    Dense(128, activation='relu'),

    Dense(64, activation='relu'),

    Dense(32, activation='relu'),

    Dense(2, activation='softmax')
])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 0.6830 - loss: 0.6086 - val_accuracy: 0.7857 - val_loss: 0.5480
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7696 - loss: 0.5052 - val_accuracy: 0.7792 - val_loss: 0.5025
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8072 - loss: 0.4410 - val_accuracy: 0.8117 - val_loss: 0.4538
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8611 - loss: 0.3739 - val_accuracy: 0.8571 - val_loss: 0.3828
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9248 - loss: 0.2997 - val_accuracy: 0.9091 - val_loss: 0.3166
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9706 - loss: 0.2227 - val_accuracy: 0.9286 - val_loss: 0.2420
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9837 - loss: 0.1506 - val_accuracy: 0.9675 - val_loss: 0.1708
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9918 - loss: 0.0964 - val_accuracy: 0.9740 - val_loss: 0.1305
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0604 - val_accuracy: 0.9870 - val_loss: 0.0950
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9967 - loss: 0.0391 - val_accuracy: 0.9805 - val_loss: 0.0819
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0256 - val_accuracy: 0.9870 - val_loss: 0.0660
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0170 - val_accuracy: 0.9870 - val_loss: 0.0638
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0120 - val_accuracy: 0.9870 - val_loss: 0.0611
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0092 - val_accuracy: 0.9870 - val_loss: 0.0601
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0070 - val_accuracy: 0.9870 - val_loss: 0.0597
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0055 - val_accuracy: 0.9870 - val_loss: 0.0596
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.9870 - val_loss: 0.0597
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0038 - val_accuracy: 0.9870 - val_loss: 0.0586
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.9870 - val_loss: 0.0595
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.9870 - val_loss: 0.0575
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.9870 - val_loss: 0.0609
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9870 - val_loss: 0.0579
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9870 - val_loss: 0.0598
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9870 - val_loss: 0.0588
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.9870 - val_loss: 0.0598
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9870 - val_loss: 0.0617
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9870 - val_loss: 0.0614
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.9870 - val_loss: 0.0604
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.3600e-04 - val_accuracy: 0.9870 - val_loss: 0.0613
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.5213e-04 - val_accuracy: 0.9870 - val_loss: 0.0626
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 7.7446e-04 - val_accuracy: 0.9870 - val_loss: 0.0629
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 7.0505e-04 - val_accuracy: 0.9870 - val_loss: 0.0635
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 6.4786e-04 - val_accuracy: 0.9870 - val_loss: 0.0638
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 6.0298e-04 - val_accuracy: 0.9870 - val_loss: 0.0632
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.5080e-04 - val_accuracy: 0.9870 - val_loss: 0.0648
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.1282e-04 - val_accuracy: 0.9870 - val_loss: 0.0650
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.7710e-04 - val_accuracy: 0.9870 - val_loss: 0.0654
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.4581e-04 - val_accuracy: 0.9870 - val_loss: 0.0651
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.1279e-04 - val_accuracy: 0.9870 - val_loss: 0.0663
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.8817e-04 - val_accuracy: 0.9870 - val_loss: 0.0665
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.6428e-04 - val_accuracy: 0.9870 - val_loss: 0.0676
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.4248e-04 - val_accuracy: 0.9870 - val_loss: 0.0671
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.2231e-04 - val_accuracy: 0.9870 - val_loss: 0.0682
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 3.0406e-04 - val_accuracy: 0.9870 - val_loss: 0.0684
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.9080e-04 - val_accuracy: 0.9870 - val_loss: 0.0700
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.7623e-04 - val_accuracy: 0.9870 - val_loss: 0.0688
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.5720e-04 - val_accuracy: 0.9870 - val_loss: 0.0694
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.4276e-04 - val_accuracy: 0.9870 - val_loss: 0.0689
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.3018e-04 - val_accuracy: 0.9870 - val_loss: 0.0673
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.1674e-04 - val_accuracy: 0.9870 - val_loss: 0.0687
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.0615e-04 - val_accuracy: 0.9870 - val_loss: 0.0686
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.9749e-04 - val_accuracy: 0.9870 - val_loss: 0.0693
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.8685e-04 - val_accuracy: 0.9870 - val_loss: 0.0709
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.7833e-04 - val_accuracy: 0.9870 - val_loss: 0.0715
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.7023e-04 - val_accuracy: 0.9870 - val_loss: 0.0712
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.6238e-04 - val_accuracy: 0.9870 - val_loss: 0.0723
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.5532e-04 - val_accuracy: 0.9870 - val_loss: 0.0715
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.4821e-04 - val_accuracy: 0.9870 - val_loss: 0.0721
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.4237e-04 - val_accuracy: 0.9870 - val_loss: 0.0729
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.3623e-04 - val_accuracy: 0.9870 - val_loss: 0.0729
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.3086e-04 - val_accuracy: 0.9870 - val_loss: 0.0732
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.2544e-04 - val_accuracy: 0.9870 - val_loss: 0.0740
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.2061e-04 - val_accuracy: 0.9870 - val_loss: 0.0744
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.1580e-04 - val_accuracy: 0.9870 - val_loss: 0.0748
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.1159e-04 - val_accuracy: 0.9870 - val_loss: 0.0743
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.0714e-04 - val_accuracy: 0.9870 - val_loss: 0.0748
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.0318e-04 - val_accuracy: 0.9870 - val_loss: 0.0755
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.9412e-05 - val_accuracy: 0.9870 - val_loss: 0.0751
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.5857e-05 - val_accuracy: 0.9870 - val_loss: 0.0762
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.2724e-05 - val_accuracy: 0.9870 - val_loss: 0.0764
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.9409e-05 - val_accuracy: 0.9870 - val_loss: 0.0777
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.6332e-05 - val_accuracy: 0.9870 - val_loss: 0.0779
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.3060e-05 - val_accuracy: 0.9870 - val_loss: 0.0769
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.0227e-05 - val_accuracy: 0.9870 - val_loss: 0.0763
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 7.7475e-05 - val_accuracy: 0.9870 - val_loss: 0.0772
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 7.4536e-05 - val_accuracy: 0.9870 - val_loss: 0.0777
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.1888e-05 - val_accuracy: 0.9870 - val_loss: 0.0780
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 6.9856e-05 - val_accuracy: 0.9870 - val_loss: 0.0783
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 6.7314e-05 - val_accuracy: 0.9870 - val_loss: 0.0780
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 6.5286e-05 - val_accuracy: 0.9870 - val_loss: 0.0795
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 6.3117e-05 - val_accuracy: 0.9870 - val_loss: 0.0784
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 6.0889e-05 - val_accuracy: 0.9870 - val_loss: 0.0795
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.8912e-05 - val_accuracy: 0.9870 - val_loss: 0.0795
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.7303e-05 - val_accuracy: 0.9870 - val_loss: 0.0793
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.5084e-05 - val_accuracy: 0.9870 - val_loss: 0.0789
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.3679e-05 - val_accuracy: 0.9870 - val_loss: 0.0800
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.1910e-05 - val_accuracy: 0.9870 - val_loss: 0.0797
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.0347e-05 - val_accuracy: 0.9870 - val_loss: 0.0787
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.9040e-05 - val_accuracy: 0.9870 - val_loss: 0.0787
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.7412e-05 - val_accuracy: 0.9870 - val_loss: 0.0798
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.5951e-05 - val_accuracy: 0.9870 - val_loss: 0.0804
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.4651e-05 - val_accuracy: 0.9870 - val_loss: 0.0807
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.3413e-05 - val_accuracy: 0.9870 - val_loss: 0.0808
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.2361e-05 - val_accuracy: 0.9870 - val_loss: 0.0797
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.1064e-05 - val_accuracy: 0.9870 - val_loss: 0.0801
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.9892e-05 - val_accuracy: 0.9870 - val_loss: 0.0802
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.8739e-05 - val_accuracy: 0.9870 - val_loss: 0.0808
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.7648e-05 - val_accuracy: 0.9870 - val_loss: 0.0817
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.6656e-05 - val_accuracy: 0.9870 - val_loss: 0.0818
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.5654e-05 - val_accuracy: 0.9870 - val_loss: 0.0823

In [31]:
loss, acc = model.evaluate(X_test, y_test)
print(f"Acc: {acc * 100:.2f}%")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9792 - loss: 0.0726
Acc: 97.92%

In [32]:
from tensorflow.keras.models import load_model

model.save('tic-tac-toe.keras')

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [33]:
import numpy as np
from tensorflow.keras.models import load_model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

model_loaded = load_model('tic-tac-toe.keras')

# Predict class probabilities
y_pred_probs = model_loaded.predict(X_test)

# Convert probabilities to class predictions
y_pred = y_pred_probs.argmax(axis=1)
y_true = y_test  # original integer labels

# Compute metrics
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred, average='weighted')
rec = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')

print(f"Accuracy : {acc:.4f}")
print(f"Precision : {prec:.4f}")
print(f"Recall : {rec:.4f}")
print(f"F1 Score : {f1:.4f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Accuracy : 0.9792
Precision : 0.9798
Recall : 0.9792
F1 Score : 0.9790

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [34]:
from tensorflow.keras.optimizers import Adam

model_v2 = Sequential([
    Dense(128, activation='relu'),

    Dense(64, activation='relu'),

    Dense(32, activation='relu'),

    Dense(2, activation='softmax')
])

model_v2.compile(optimizer=Adam(learning_rate=0.001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model_v2.fit(X_train, y_train, epochs=30, validation_split=0.2)

loss_v2, acc_v2 = model_v2.evaluate(X_test, y_test)
print(f"Model v2 (30 epochs) -> Loss: {loss_v2:.4f}, Acc: {acc_v2 * 100:.2f}%")

Epoch 1/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.7108 - loss: 0.5955 - val_accuracy: 0.7662 - val_loss: 0.5415
Epoch 2/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7663 - loss: 0.5097 - val_accuracy: 0.7922 - val_loss: 0.5107
Epoch 3/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8154 - loss: 0.4444 - val_accuracy: 0.8052 - val_loss: 0.4576
Epoch 4/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8742 - loss: 0.3776 - val_accuracy: 0.8701 - val_loss: 0.4029
Epoch 5/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9118 - loss: 0.3108 - val_accuracy: 0.9091 - val_loss: 0.3391
Epoch 6/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9690 - loss: 0.2422 - val_accuracy: 0.9091 - val_loss: 0.2712
Epoch 7/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9510 - loss: 0.1912 - val_accuracy: 0.9545 - val_loss: 0.2074
Epoch 8/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9853 - loss: 0.1260 - val_accuracy: 0.9610 - val_loss: 0.1686
Epoch 9/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9902 - loss: 0.0880 - val_accuracy: 0.9740 - val_loss: 0.1221
Epoch 10/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9935 - loss: 0.0592 - val_accuracy: 0.9740 - val_loss: 0.0927
Epoch 11/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9984 - loss: 0.0376 - val_accuracy: 0.9740 - val_loss: 0.0780
Epoch 12/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0245 - val_accuracy: 0.9740 - val_loss: 0.0642
Epoch 13/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0176 - val_accuracy: 0.9740 - val_loss: 0.0551
Epoch 14/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0128 - val_accuracy: 0.9870 - val_loss: 0.0445
Epoch 15/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0100 - val_accuracy: 0.9870 - val_loss: 0.0431
Epoch 16/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0076 - val_accuracy: 0.9870 - val_loss: 0.0425
Epoch 17/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0061 - val_accuracy: 0.9870 - val_loss: 0.0382
Epoch 18/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0053 - val_accuracy: 0.9870 - val_loss: 0.0345
Epoch 19/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.9870 - val_loss: 0.0371
Epoch 20/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.9870 - val_loss: 0.0342
Epoch 21/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.9870 - val_loss: 0.0315
Epoch 22/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9870 - val_loss: 0.0319
Epoch 23/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.9870 - val_loss: 0.0299
Epoch 24/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.9870 - val_loss: 0.0315
Epoch 25/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9870 - val_loss: 0.0287
Epoch 26/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9870 - val_loss: 0.0308
Epoch 27/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.9870 - val_loss: 0.0308
Epoch 28/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9870 - val_loss: 0.0295
Epoch 29/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9870 - val_loss: 0.0290
Epoch 30/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9870 - val_loss: 0.0283
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9844 - loss: 0.0362
Model v2 (30 epochs) -> Loss: 0.0362, Acc: 98.44%

In [40]:
# Quick comparison of all models tried
print(f"{'Model:'} | {'Loss':<8} | {'Accuracy'}")
print(f"{'v1:   '} | {loss:<8.4f} | {acc * 100:.2f}%")
print(f"{'v2:   '} | {loss_v2:<8.4f} | {acc_v2 * 100:.2f}%")

Model: | Loss     | Accuracy
v1:    | 0.0726   | 97.92%
v2:    | 0.0362   | 98.44%

**Which approach(es) did you find helpful to improve your model performance?**

In [41]:
# The conclusion is, reducing Epochs from 100 to 30 helps to get less loss value
# and better Accuracy. Thre previous results show us overfitting and is still there.