# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving tic-tac-toe.csv to tic-tac-toe (3).csv

In [ ]:
# your code here
data = pd.read_csv('tic-tac-toe.csv')
df = data.copy()
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [ ]:
df.nunique()

TL       3
TM       3
TR       3
ML       3
MM       3
MR       3
BL       3
BM       3
BR       3
class    2
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [ ]:
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

/tmp/ipykernel_2146/242626680.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [ ]:
mapping = {'x':1, 'o':-1, 'b':0}
for col in df.columns[:-1]:
  df[col] = df[col].map(mapping)

In [ ]:
df['class'].unique()

array([ True, False])

In [ ]:
df['class'] = df['class'].astype(int)
df

     TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0     1   1   1   1  -1  -1   1  -1  -1      1
1     1   1   1   1  -1  -1  -1   1  -1      1
2     1   1   1   1  -1  -1  -1  -1   1      1
3     1   1   1   1  -1  -1  -1   0   0      1
4     1   1   1   1  -1  -1   0  -1   0      1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
953  -1   1   1   1  -1  -1  -1   1   1      0
954  -1   1  -1   1   1  -1   1  -1   1      0
955  -1   1  -1   1  -1   1   1  -1   1      0
956  -1   1  -1  -1   1   1   1  -1   1      0
957  -1  -1   1   1   1  -1  -1   1   1      0

[958 rows x 10 columns]

In [ ]:
X=df.iloc[:, :-1]
y = df.iloc[:, -1]
display(X.shape, y.shape)

(958, 9)

(958,)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_scaled

array([[ 1.03516957,  1.10682993,  1.03516957, ...,  1.03516957,
        -1.2235944 , -1.23155602],
       [ 1.03516957,  1.10682993,  1.03516957, ..., -1.23155602,
         1.10682993, -1.23155602],
       [ 1.03516957,  1.10682993,  1.03516957, ..., -1.23155602,
        -1.2235944 ,  1.03516957],
       ...,
       [-1.23155602,  1.10682993, -1.23155602, ...,  1.03516957,
        -1.2235944 ,  1.03516957],
       [-1.23155602,  1.10682993, -1.23155602, ...,  1.03516957,
        -1.2235944 ,  1.03516957],
       [-1.23155602, -1.2235944 ,  1.03516957, ..., -1.23155602,
         1.10682993,  1.03516957]])

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [ ]:
from sklearn.model_selection import train_test_split
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Dropout, Input, Flatten

In [ ]:
# your code here
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, test_size=0.2, random_state=42)

In [ ]:
model = Sequential()

In [ ]:
model.add(layers.Dense(8, activation='relu', input_shape = (9,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                │ (None, 8)              │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 241 (964.00 B)

 Trainable params: 241 (964.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train,
                    batch_size=32,
                    epochs=30,
                    validation_data=((X_test, y_test)))

Epoch 1/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.5561 - loss: 0.6905 - val_accuracy: 0.6250 - val_loss: 0.6705
Epoch 2/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6619 - loss: 0.6452 - val_accuracy: 0.7135 - val_loss: 0.6424
Epoch 3/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7063 - loss: 0.6177 - val_accuracy: 0.7135 - val_loss: 0.6237
Epoch 4/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7285 - loss: 0.5977 - val_accuracy: 0.7188 - val_loss: 0.6109
Epoch 5/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7337 - loss: 0.5817 - val_accuracy: 0.7135 - val_loss: 0.5998
Epoch 6/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7363 - loss: 0.5685 - val_accuracy: 0.7188 - val_loss: 0.5904
Epoch 7/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7441 - loss: 0.5564 - val_accuracy: 0.7240 - val_loss: 0.5822
Epoch 8/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7546 - loss: 0.5456 - val_accuracy: 0.7240 - val_loss: 0.5740
Epoch 9/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7507 - loss: 0.5354 - val_accuracy: 0.7292 - val_loss: 0.5660
Epoch 10/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7533 - loss: 0.5266 - val_accuracy: 0.7396 - val_loss: 0.5559
Epoch 11/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7611 - loss: 0.5174 - val_accuracy: 0.7396 - val_loss: 0.5480
Epoch 12/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7650 - loss: 0.5073 - val_accuracy: 0.7500 - val_loss: 0.5375
Epoch 13/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7650 - loss: 0.4978 - val_accuracy: 0.7448 - val_loss: 0.5278
Epoch 14/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7715 - loss: 0.4886 - val_accuracy: 0.7552 - val_loss: 0.5193
Epoch 15/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7715 - loss: 0.4801 - val_accuracy: 0.7604 - val_loss: 0.5085
Epoch 16/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7768 - loss: 0.4702 - val_accuracy: 0.7604 - val_loss: 0.4997
Epoch 17/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7820 - loss: 0.4602 - val_accuracy: 0.7708 - val_loss: 0.4903
Epoch 18/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7833 - loss: 0.4497 - val_accuracy: 0.7656 - val_loss: 0.4790
Epoch 19/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7963 - loss: 0.4380 - val_accuracy: 0.7865 - val_loss: 0.4683
Epoch 20/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8068 - loss: 0.4273 - val_accuracy: 0.7865 - val_loss: 0.4577
Epoch 21/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8238 - loss: 0.4155 - val_accuracy: 0.7812 - val_loss: 0.4434
Epoch 22/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8316 - loss: 0.4019 - val_accuracy: 0.8073 - val_loss: 0.4326
Epoch 23/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8407 - loss: 0.3895 - val_accuracy: 0.8177 - val_loss: 0.4194
Epoch 24/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8473 - loss: 0.3753 - val_accuracy: 0.8177 - val_loss: 0.4049
Epoch 25/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8564 - loss: 0.3613 - val_accuracy: 0.8333 - val_loss: 0.3893
Epoch 26/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8695 - loss: 0.3458 - val_accuracy: 0.8542 - val_loss: 0.3724
Epoch 27/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8877 - loss: 0.3298 - val_accuracy: 0.8594 - val_loss: 0.3563
Epoch 28/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8943 - loss: 0.3129 - val_accuracy: 0.8802 - val_loss: 0.3392
Epoch 29/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9099 - loss: 0.2954 - val_accuracy: 0.9062 - val_loss: 0.3171
Epoch 30/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9204 - loss: 0.2754 - val_accuracy: 0.9167 - val_loss: 0.2987

In [ ]:
score =model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.2986892759799957
Test accuracy: 0.9166666865348816

In [ ]:
model.save('tic-tac-toe.keras')

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [ ]:
import tensorflow as tf

In [ ]:
# your code here
my_model = tf.keras.models.load_model('tic-tac-toe.keras')

In [ ]:
predictions = my_model.predict(X_test)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [ ]:
# your code here
model2 = Sequential()
model2.add(layers.Dense(16, activation='relu', input_shape = (9,)))
model2.add(layers.Dense(32, activation='relu'))
model2.add(layers.Dense(16, activation='relu'))
model2.add(layers.Dense(1, activation='sigmoid'))

model2.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [ ]:
history2 = model2.fit(X_train, y_train,
                    batch_size=32,
                    epochs=30,
                    validation_data=((X_test, y_test)))

Epoch 1/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.4856 - loss: 0.7059 - val_accuracy: 0.6667 - val_loss: 0.6600
Epoch 2/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6606 - loss: 0.6399 - val_accuracy: 0.6875 - val_loss: 0.6209
Epoch 3/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6802 - loss: 0.6065 - val_accuracy: 0.6927 - val_loss: 0.5963
Epoch 4/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7089 - loss: 0.5810 - val_accuracy: 0.7344 - val_loss: 0.5758
Epoch 5/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7376 - loss: 0.5558 - val_accuracy: 0.7396 - val_loss: 0.5604
Epoch 6/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7650 - loss: 0.5338 - val_accuracy: 0.7604 - val_loss: 0.5465
Epoch 7/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7781 - loss: 0.5146 - val_accuracy: 0.7604 - val_loss: 0.5353
Epoch 8/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7898 - loss: 0.4945 - val_accuracy: 0.7656 - val_loss: 0.5225
Epoch 9/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7872 - loss: 0.4804 - val_accuracy: 0.7708 - val_loss: 0.5116
Epoch 10/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8068 - loss: 0.4598 - val_accuracy: 0.7760 - val_loss: 0.4971
Epoch 11/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4409 - val_accuracy: 0.7865 - val_loss: 0.4799
Epoch 12/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8238 - loss: 0.4175 - val_accuracy: 0.8021 - val_loss: 0.4641
Epoch 13/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8368 - loss: 0.3937 - val_accuracy: 0.8021 - val_loss: 0.4406
Epoch 14/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8551 - loss: 0.3675 - val_accuracy: 0.8333 - val_loss: 0.4165
Epoch 15/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8799 - loss: 0.3422 - val_accuracy: 0.8438 - val_loss: 0.3914
Epoch 16/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8982 - loss: 0.3114 - val_accuracy: 0.8750 - val_loss: 0.3567
Epoch 17/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9125 - loss: 0.2808 - val_accuracy: 0.8854 - val_loss: 0.3302
Epoch 18/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9256 - loss: 0.2508 - val_accuracy: 0.8906 - val_loss: 0.2990
Epoch 19/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9373 - loss: 0.2224 - val_accuracy: 0.9062 - val_loss: 0.2709
Epoch 20/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9452 - loss: 0.1944 - val_accuracy: 0.9219 - val_loss: 0.2416
Epoch 21/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9543 - loss: 0.1701 - val_accuracy: 0.9427 - val_loss: 0.2119
Epoch 22/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9700 - loss: 0.1456 - val_accuracy: 0.9583 - val_loss: 0.1922
Epoch 23/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9804 - loss: 0.1244 - val_accuracy: 0.9583 - val_loss: 0.1748
Epoch 24/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9830 - loss: 0.1068 - val_accuracy: 0.9635 - val_loss: 0.1547
Epoch 25/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9869 - loss: 0.0907 - val_accuracy: 0.9635 - val_loss: 0.1395
Epoch 26/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9883 - loss: 0.0787 - val_accuracy: 0.9635 - val_loss: 0.1319
Epoch 27/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9896 - loss: 0.0676 - val_accuracy: 0.9740 - val_loss: 0.1186
Epoch 28/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9909 - loss: 0.0595 - val_accuracy: 0.9792 - val_loss: 0.1101
Epoch 29/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9909 - loss: 0.0517 - val_accuracy: 0.9792 - val_loss: 0.1031
Epoch 30/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0459 - val_accuracy: 0.9792 - val_loss: 0.1009

In [ ]:
score2 =model2.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score2[0])
print('Test accuracy:', score2[1])

Test loss: 0.10086259245872498
Test accuracy: 0.9791666865348816

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here

adding another layer improved the model accuracy